name: Deploy GitHub Pages

on:
  push:
    branches:
      - master
 
# 任务
jobs:
  build-and-deploy:
    # 服务器环境：最新版 Ubuntu
    runs-on: ubuntu-latest
    steps:
      # 拉取代码
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false
 
      # 同步到 gitee 的仓库
      - name: Sync to Gitee
        uses: wearerequired/git-mirror-action@master
        env:
          SSH_PRIVATE_KEY: ${{ secrets.GITEE_RSA_PRIVATE_KEY }}
        with:
          source-repo: git@github.com:chick26/Note_Backup.git
          destination-repo: git@gitee.com:chick-lee/chick-obsidian-repo.git
 
      # 部署到 Gitee Pages
      - name: Build Gitee Pages
        uses: yanglbme/gitee-pages-action@main
        with:
          gitee-username: lizhicheng26@outlook.com
          gitee-password: ${{ secrets.GITEE_PASSWORD }}
          gitee-repo: chick-lee/chick-obsidian-repo
          branch: master
 
